export const Colors = {
	// Default
	WHITE: '#FFFFFF',
	BLACK: '#000000',
	GRAY: '#C1C1C1',

	// Background
	BACKGROUND_MAIN: '#FAFAFA',
	BACKGROUND_SUB: '#F3F0F5',
	BACKGROUND_DIM: 'rgba(0, 0, 0, 0.20)',

	// Body Text
	BODYTEXT_MAIN: '#202020',
	BODYTEXT_SUB: '#757474',
	BODYTEXT_SUB_2: '#BCBCBC',
	BODYTEXT_DISABLED: '#C1C1C1',

	// Button
	BUTTON_SELECTED: '#874FFF',
	BUTTON_PUSH: '#4F2E94',
	BUTTON_UNSELECTED: '#C1C1C1',
	BUTTON_DESTRUCTIVE: '#E53935',

	// Text / Button
	TEXT_BUTTON_SELECTED: '#FFFFFF',
	TEXT_BUTTON_UNSELECTED: '#C1C1C1',

	// Textbox
	TEXTBOX_SELECTED: '#EAEAEA',
	TEXTBOX_UNSELECTED: '#EAEAEA',

	// Point Color
	POINTCOLOR: '#874FFF',
	POINTCOLOR_10: 'rgba(135, 79, 255, 0.1)',
	POINTCOLOR_SUB: '#FFFFFF',

	// Icon
	ICON_SELECTED: '#202020',
	ICON_UNSELECTED: '#202020',

	// Footer
	FOOTER_COLOR: '#FAFAFA',

	// Category Background (pastel)
	CATEGORY_BACKGROUND_ACADEMIC: '#E5EEFA',
	CATEGORY_BACKGROUND_RELIGION: '#F7F6F3',
	CATEGORY_BACKGROUND_VOLUNTEER: '#FAEFE8',
	CATEGORY_BACKGROUND_PERFORMANCE: '#F8FAEC',
	CATEGORY_BACKGROUND_WORKOUT: '#EEF7F6',
	CATEGORY_BACKGROUND_PROMOTION: '#FAF6EB',
	CATEGORY_BACKGROUND_HOBBY: '#F9EAED',
	CATEGORY_BACKGROUND_CULTURE: '#F3F5F0',
	CATEGORY_BACKGROUND_CAREER: '#EEEDED',

	// Category Solid
	CATEGORY_ACADEMIC: '#2486FF',
	CATEGORY_RELIGION: '#947C4F',
	CATEGORY_VOLUNTEER: '#FF8F4A',
	CATEGORY_PERFORMANCE: '#B7CA2E',
	CATEGORY_SPORTS: '#2A9D91',
	CATEGORY_PROMOTION: '#E49E05',
	CATEGORY_HOBBY: '#F05678',
	CATEGORY_CULTURE: '#739437',
	CATEGORY_CAREER: '#847876',
}
