export const Colors = {
	// Default
	WHITE: '#FFFFFF',
	BLACK: '#000000',
	GRAY: '#C1C1C1',

	// Background
	BACKGROUND_MAIN: '#FAFAFA',
	BACKGROUND_SUB: '#F3F0F5',

	// Body Text
	BODYTEXT_MAIN: '#202020',
	BODYTEXT_SUB: '#757474',
	BODYTEXT_DISABLED: '#C1C1C1',

	// Button
	BUTTON_SELECTED: '#874FFF',
	BUTTON_UNSELECTED: '#C1C1C1',

	// Text / Button
	TEXT_BUTTON_SELECTED: '#FFFFFF',
	TEXT_BUTTON_UNSELECTED: '#C1C1C1',

	// Textbox
	TEXTBOX_SELECTED: '#EAEAEA',
	TEXTBOX_UNSELECTED: '#EAEAEA',

	// Point Color
	POINTCOLOR: '#874FFF',
	POINTCOLOR_SUB: '#FFFFFF',

	// Icon
	ICON_SELECTED: '#202020',
	ICON_UNSELECTED: '#202020',

	// Footer
	FOOTER_COLOR: '#FAFAFA',

	// Category Background (pastel)
	CATEGORY_BACKGROUND_ACADEMIC: '#E5EEFA',
	CATEGORY_BACKGROUND_RELIGION: '#F7F6F3',
	CATEGORY_BACKGROUND_VOLUNTEER: '#FAEFE8',
	CATEGORY_BACKGROUND_PERFORMANCE: '#E6F672',
	CATEGORY_BACKGROUND_WORKOUT: '#86E0D7',
	CATEGORY_BACKGROUND_PROMOTION: '#FFCE62',
	CATEGORY_BACKGROUND_HOBBY: '#F05678',
	CATEGORY_BACKGROUND_CULTURE: '#B7C995',
	CATEGORY_BACKGROUND_CAREER: '#847876',

	// Category Solid
	CATEGORY_ACADEMIC: '#2486FF',
	CATEGORY_RELIGION: '#DDD0B8',
	CATEGORY_VOLUNTEER: '#FF8F4A',
	CATEGORY_PERFORMANCE: '#E6F672',
	CATEGORY_SPORTS: '#86E0D7',
	CATEGORY_PROMOTION: '#FFCE62',
	CATEGORY_HOBBY: '#F05678',
	CATEGORY_CULTURE: '#B7C995',
	CATEGORY_CAREER: '#847876',
}
